import logging
import os
from typing import Optional
import fal_client
import openai

from app.core.config import config
from app.utils.media_uploader import media_uploader

logger = logging.getLogger(__name__)


class AudioGenerationService:
    """Consolidated service for audio generation - MiniMax Music"""

    def __init__(self):
        """Initialize FAL.ai and OpenAI clients for audio generation"""
        # FAL.ai for MiniMax Music
        if not config.FAL_API_KEY:
            raise ValueError("FAL_API_KEY is required for audio generation")
        os.environ["FAL_KEY"] = config.FAL_API_KEY
        fal_client.api_key = config.FAL_API_KEY
        
        # OpenAI for prompt enhancement
        if not config.OPEN_AI_API_KEY:
            raise ValueError("OPEN_AI_API_KEY is required for prompt enhancement")
        self.openai_client = openai.OpenAI(api_key=config.OPEN_AI_API_KEY)
        
        # Media uploader for storage
        self.uploader = media_uploader

    async def generate_audio(
        self,
        verse_prompt: str,
        user_id: str,
        lyrics_prompt: Optional[str] = None
    ) -> str:
        """
        Generate audio using MiniMax Music via FAL.ai

        Args:
            verse_prompt: The actual lyrics content/text (will be enhanced)
            user_id: User ID for file organization
            lyrics_prompt: Optional music style description (will be enhanced if provided)

        Returns:
            Audio URL (GCS or local)
        """
        try:
            logger.info(f"Generating music with MiniMax for lyrics: {verse_prompt[:50]}...")
            
            # ==================== ENHANCE VERSE (LYRICS) ====================
            verse_system_prompt = """You are an expert at writing verses. 
            Take the user's prompt and write creative and engaging verses that fit the prompt provided. MUST BE UNDER 300 CHARACTERS."""
            
            verse_user_message = f"""Write verses based on this prompt: "{verse_prompt}"
            
            Return only the enhanced verses, no explanations."""

            verse_response = self.openai_client.chat.completions.create(
                model="gpt-4o",
                messages=[
                    {"role": "system", "content": verse_system_prompt},
                    {"role": "user", "content": verse_user_message}
                ],
                max_tokens=300,
                temperature=0.7
            )
            
            enhanced_verses = verse_response.choices[0].message.content.strip()
            if len(enhanced_verses) > 300:
                enhanced_verses = enhanced_verses[:297] + "..."
            
            # ==================== ENHANCE MUSIC STYLE (OPTIONAL) ====================
            enhanced_music_style = None
            if lyrics_prompt and lyrics_prompt.strip():
                logger.info(f"Enhancing music style: {lyrics_prompt[:50]}...")
                
                style_system_prompt = """You are an expert at writing music style. Take the user's prompt and write a precise music style descriptions that fit the prompt provided."""
                
                style_user_message = f"""Write a music style description based on this prompt: "{lyrics_prompt}"
                
                Return only the enhanced prompt, no explanations."""

                style_response = self.openai_client.chat.completions.create(
                    model="gpt-4o",
                    messages=[
                        {"role": "system", "content": style_system_prompt},
                        {"role": "user", "content": style_user_message}
                    ],
                    max_tokens=300,
                    temperature=0.7
                )
                
                enhanced_music_style = style_response.choices[0].message.content.strip()
                if len(enhanced_music_style) > 300:
                    enhanced_music_style = enhanced_music_style[:297] + "..."
            
            # ==================== GENERATE AUDIO WITH MINIMAX ====================
            fal_arguments = {
                "prompt": enhanced_verses,
                "lyrics_prompt": enhanced_music_style if enhanced_music_style and enhanced_music_style.strip() 
                                else "A melodic and harmonious composition"
            }
            
            handler = fal_client.submit(
                "fal-ai/minimax-music/v1.5",
                arguments=fal_arguments
            )
            
            result = handler.get()
            
            if not result or "audio" not in result or not result["audio"]:
                raise Exception("No audio generated by MiniMax")
            
            audio_url = result["audio"]["url"]
            
            # Download and save
            return await self.uploader.upload_audio_from_url(audio_url, verse_prompt, user_id, "minimax_music")
            
        except Exception as e:
            logger.error(f"Error generating audio: {str(e)}")
            raise




audio_generation_service = AudioGenerationService()
